/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "convert.h"

bool_t
xdr_conversion_args (XDR *xdrs, conversion_args *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}
