/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct addition_args {
	int a;
	int b;
};
typedef struct addition_args addition_args;

#define CALCUL_PROG 0x20000001
#define CALCUL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define factorial 1
extern  int * factorial_1(int *, CLIENT *);
extern  int * factorial_1_svc(int *, struct svc_req *);
#define addition 2
extern  int * addition_1(addition_args *, CLIENT *);
extern  int * addition_1_svc(addition_args *, struct svc_req *);
extern int calcul_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define factorial 1
extern  int * factorial_1();
extern  int * factorial_1_svc();
#define addition 2
extern  int * addition_1();
extern  int * addition_1_svc();
extern int calcul_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_addition_args (XDR *, addition_args*);

#else /* K&R C */
extern bool_t xdr_addition_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
