/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONVERSION_H_RPCGEN
#define _CONVERSION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct conversion_args {
	float value;
};
typedef struct conversion_args conversion_args;

#define CONVERSION_PROG 0x20000002
#define CONVERSION_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define KM_TO_MILES 1
extern  float * km_to_miles_1(conversion_args *, CLIENT *);
extern  float * km_to_miles_1_svc(conversion_args *, struct svc_req *);
#define CELSIUS_TO_FAHRENHEIT 2
extern  float * celsius_to_fahrenheit_1(conversion_args *, CLIENT *);
extern  float * celsius_to_fahrenheit_1_svc(conversion_args *, struct svc_req *);
extern int conversion_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define KM_TO_MILES 1
extern  float * km_to_miles_1();
extern  float * km_to_miles_1_svc();
#define CELSIUS_TO_FAHRENHEIT 2
extern  float * celsius_to_fahrenheit_1();
extern  float * celsius_to_fahrenheit_1_svc();
extern int conversion_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_conversion_args (XDR *, conversion_args*);

#else /* K&R C */
extern bool_t xdr_conversion_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONVERSION_H_RPCGEN */
