/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params {
	int a;
	int b;
};
typedef struct params params;

#define CALCUL_PROG 0x20000001
#define CALCUL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define addition 1
extern  int * addition_1(params *, CLIENT *);
extern  int * addition_1_svc(params *, struct svc_req *);
#define multiplication 2
extern  int * multiplication_1(params *, CLIENT *);
extern  int * multiplication_1_svc(params *, struct svc_req *);
#define soustraction 2
extern  int * soustraction_1(params *, CLIENT *);
extern  int * soustraction_1_svc(params *, struct svc_req *);
#define absolu 1
extern  int * absolu_1(int *, CLIENT *);
extern  int * absolu_1_svc(int *, struct svc_req *);
extern int calcul_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addition 1
extern  int * addition_1();
extern  int * addition_1_svc();
#define multiplication 2
extern  int * multiplication_1();
extern  int * multiplication_1_svc();
#define soustraction 2
extern  int * soustraction_1();
extern  int * soustraction_1_svc();
#define absolu 1
extern  int * absolu_1();
extern  int * absolu_1_svc();
extern int calcul_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
