/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"


void
calcul_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	params  addition_1_arg;
	int  *result_2;
	params  multiplication_1_arg;
	int  *result_3;
	params  soustraction_1_arg;
	int  *result_4;
	int  absolu_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL_PROG, CALCUL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = addition_1(&addition_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = multiplication_1(&multiplication_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = soustraction_1(&soustraction_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = absolu_1(&absolu_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calcul_prog_1 (host);
exit (0);
}
