/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTACT_H_RPCGEN
#define _CONTACT_H_RPCGEN

#include <tirpc/rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Contact {
	char *nom;
	char *numero;
};
typedef struct Contact Contact;

struct ContactList {
	struct {
		u_int contacts_len;
		Contact *contacts_val;
	} contacts;
};
typedef struct ContactList ContactList;

#define CONTACT_PROG 0x31234567
#define CONTACT_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define ajouterContact 1
extern  int * ajoutercontact_1(Contact *, CLIENT *);
extern  int * ajoutercontact_1_svc(Contact *, struct svc_req *);
#define rechercherContact 2
extern  char ** recherchercontact_1(char **, CLIENT *);
extern  char ** recherchercontact_1_svc(char **, struct svc_req *);
#define supprimerContact 3
extern  int * supprimercontact_1(char **, CLIENT *);
extern  int * supprimercontact_1_svc(char **, struct svc_req *);
#define afficherContacts 4
extern  ContactList * affichercontacts_1(void *, CLIENT *);
extern  ContactList * affichercontacts_1_svc(void *, struct svc_req *);
extern int contact_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ajouterContact 1
extern  int * ajoutercontact_1();
extern  int * ajoutercontact_1_svc();
#define rechercherContact 2
extern  char ** recherchercontact_1();
extern  char ** recherchercontact_1_svc();
#define supprimerContact 3
extern  int * supprimercontact_1();
extern  int * supprimercontact_1_svc();
#define afficherContacts 4
extern  ContactList * affichercontacts_1();
extern  ContactList * affichercontacts_1_svc();
extern int contact_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Contact (XDR *, Contact*);
extern  bool_t xdr_ContactList (XDR *, ContactList*);

#else /* K&R C */
extern bool_t xdr_Contact ();
extern bool_t xdr_ContactList ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTACT_H_RPCGEN */
