/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "contact.h"

bool_t
xdr_Contact (XDR *xdrs, Contact *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nom, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->numero, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ContactList (XDR *xdrs, ContactList *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->contacts.contacts_val, (u_int *) &objp->contacts.contacts_len, 100,
		sizeof (Contact), (xdrproc_t) xdr_Contact))
		 return FALSE;
	return TRUE;
}
