/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CALCUL_PROG 0x20000000
#define CALCUL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define addition 1
extern  int * addition_1(operandes *, CLIENT *);
extern  int * addition_1_svc(operandes *, struct svc_req *);
#define soustraction 2
extern  int * soustraction_1(operandes *, CLIENT *);
extern  int * soustraction_1_svc(operandes *, struct svc_req *);
#define multiplication 3
extern  int * multiplication_1(operandes *, CLIENT *);
extern  int * multiplication_1_svc(operandes *, struct svc_req *);
#define quotient 4
extern  int * quotient_1(operandes *, CLIENT *);
extern  int * quotient_1_svc(operandes *, struct svc_req *);
#define absolue 5
extern  int * absolue_1(int *, CLIENT *);
extern  int * absolue_1_svc(int *, struct svc_req *);
extern int calcul_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addition 1
extern  int * addition_1();
extern  int * addition_1_svc();
#define soustraction 2
extern  int * soustraction_1();
extern  int * soustraction_1_svc();
#define multiplication 3
extern  int * multiplication_1();
extern  int * multiplication_1_svc();
#define quotient 4
extern  int * quotient_1();
extern  int * quotient_1_svc();
#define absolue 5
extern  int * absolue_1();
extern  int * absolue_1_svc();
extern int calcul_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
